spring:
  application:
    name: ffl-backend
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  h2:
    console:
      enabled: false
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/fflng
    driver-class-name: org.postgresql.Driver
    username: admin
    password: ${DB_PASSWORD:fflng347}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false

app:
  jwt:
    expiration: 31536000000
